#!/bin/sh
mkdir -p xmlresults
CONTEXT=$1
[ -z "$context" ] || CONTEXT="global"
exec > xmlresults/${CONTEXT}.xml
echo '<?xml version="1.0"?>'
NUMTESTS=$(cat failed_tests passed_tests | wc -l)
NUMFAILED=$(cat failed_tests | wc -l)
echo '<testsuite tests="'$NUMTESTS'" failures="'$NUMFAILED'" errors="'$NUMFAILED'" name="'$CONTEXT'">'
for t in $(cat failed_tests)
do
	echo '  <testcase name="'$t'" classname="'$CONTEXT'" time="0">'
	echo '    <error type="error" message="test failed"/>'
	echo '  </testcase>'
done
echo '</testsuite>'
